# Site settings
title:  其实也是
email: i.yxl@foxmail.com
description: "hello world!......."
baseurl: 
url: "http://ixiao.github.io"
twitter_username: null
github_username:  ixiao
facebook_username:  null

# Build settings
markdown: kramdown
rouge: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: xiao
qq: 48063692
duoshuo: ixiao
weibo: 505501200
github: ixiao
safe: true
# paginate: 20
