# Site settings
title: Xiao‘Blog
email: i.yxl@foxmail.com
description: "hello world!......."
baseurl: 
url: "http://ixiao.pw"
twitter_username: iyanxiao
github_username:  ixiao
facebook_username:  100008541150823

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: 小潇
qq: 592314686
duoshuo: ixiao
weibo: 505501200
github: ixiao
pygments: true
safe: true
# paginate: 20
